### ISSUE TITLE
Newest version does NOT get installed

### ISSUE THREAD

**Issue by cscalfani** [gdotdesign/elm-github-install#28]
I had a repo go from version 4.1.0 to 4.1.1. My elm-package.json is looking for 4.0.0 <= v < 5.0.0.

Every time I run `elm-github-install`, it finds the 4.1.0 version in the cache and installs that.

The only way to get it to install correctly, is to DELETE the cache files.

**Comment by takaczapka** [comment]
Even more, if I have a new version of the package (moving from 1.1.2 to 1.1.3) and update in my project's elm-package.json to be "1.1.3 <= v < 2.0.0" it will not find it unless I delete cached version from $HOME/.elm-install/github/.

**Comment by wende** [comment]
Same here.

BTW @gdotdesign I wanted to say this project was enormous help in making https://github.com/wende/elmchemy. You're our hero 🙌

**Comment by gdotdesign** [comment]
I'm aware of this issue, and I'm planning of fixing it this week. (I was on holiday)

It comes from the fact that git repositories are decentralized and there are no single server where we could check for new versions. Currently there is no mechanism for updating repositories so only those versions are available which existed when they repository was cloned.

I'll probably do something like [Crystal](https://crystal-lang.org) does which is when checking the versions of a package we would fetch the repository (thus updating it) instead of checking the current state (which can be stale). 

A workaround is to go to the repository (in the cache folder) and do a manual `git fetch`, which would update it and the subsequent install would work after that.

> BTW @gdotdesign I wanted to say this project was enormous help in making https://github.com/wende/elmchemy. You're our hero :raised_hands:

Thanks :smile: it means a lot :+1:

**Comment by gdotdesign** [comment]
This PR should fix it https://github.com/gdotdesign/elm-github-install/pull/30 

It comes with one downside that all installs will be slower because of all the fetches that need to take place.

@takaczapka @wende @cscalfani if any of you could test it out I would be grateful,  just let me know if you need me to create a build (in case you can't install from source or from github directly).

**Comment by gdotdesign** [comment]
Released as [v1.1.0](https://github.com/gdotdesign/elm-github-install/releases/tag/v1.1.0)
