### ISSUE TITLE
`elm-install` just failing with contract failure for jRuby

### ISSUE THREAD

**Issue by RobertFischer** [gdotdesign/elm-github-install#32]
I'm getting an issue with contract violation around parsing constraints.

Here's my minimal `package.json`:
```
$ cat elm-package.json 
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.1.1 <= v < 6.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

And here's the error that I get.
```
$ elm-install 
/home/robert/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/commander-4.4.3/lib/commander/user_interaction.rb:334: warning: constant ::JavaPackageModuleTemplate is deprecated
error: Contract violation for return value:
        Expected: [Solve::Constraint],
        Actual: [#<Solve::Constraint < 6.0.0>, #<Solve::Constraint >= 5.1.1>]
        Value guarded in: ElmInstall::Utils::transform_constraint
        With Contract: String => Array
        At: /home/robert/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/elm_install-1.1.1/lib/elm_install/utils.rb:23 . Use --trace to view backtrace
```

Here's the version information, for the record:
```
$ elm-install help -v
/home/robert/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/commander-4.4.3/lib/commander/user_interaction.rb:334: warning: constant ::JavaPackageModuleTemplate is deprecated
elm-install 1.1.1
```

Any idea what is up?

**Comment by RobertFischer** [comment]
Looks like it's a jRuby issue. I used `rbenv` to change to 2.4.1 locally and it worked just fine after a reinstall.

**Comment by headius** [comment]
Looks like some array isn't getting splatted properly, so you get the array instead of its first element. Toss us a bug and we'll look into it.

**Comment by RobertFischer** [comment]
@headius -- Bug submitted. https://github.com/jruby/jruby/issues/4732

Thank you very much!

**Comment by enebo** [comment]
I fixed this for our upcoming 9.1.13.0 release.  The problem was that we fired method_added and singleton_method_added in a different order than MRI.  You may want to rethink how this works since I suspect you have a 50% chance of failing on RubyTruffle or Rbx or perhaps even MRI if someone happens to change the firing order.  It is not big deal for us to match MRI here but I thought I would chime in with my 2c.

**Comment by gdotdesign** [comment]
Thanks for looking into this :+1: :smile:  

Just to clarify If I were to remove the contracts gem, this issue would go away? Is there anything that I can do In this gem to make it less brittle?

**Comment by enebo** [comment]
@gdotdesign sorry I wrote this like you wrote the contracts gem.  Here is a bit more analysis...

There are two things at play here.  The first is for module_methods if the contracts gem recieves singleton_method_added first it replaces the definition of the module_method but not the corresponding instance method which is created by the Module.  If the order is switched then it replaces the instance method and not the module method.  I wonder if this is a bug in contracts?   It seems both copies of the method should have the contract applied?  I don't know the library though.

The second thing is JRuby was not working with the wrong order in your gem because:
```ruby
        constraints = Utils.transform_constraint constraint
```

is saying call the module_method in which the module method in MRI was not getting its definition replaced by the contract; whereas it was in JRuby.  Interestingly, in JRuby, the contract was invalid for this call.  So do you have a bug here but since MRI was only replacing the instance method of transform_constraint and in this call it is contract-free?

If I had to guess I would say there are two bugs in play here:

1. contracts should be replacing the module_method and instance method versions in a module with the contract enforcing method.
2. the call I mentioned about in elm-github-install is not honoring the specified contract.

**Comment by gdotdesign** [comment]
Thank you so much for the explanation!

This is probably a bug somewhere because `transform_constraints` should return an array with multiple elements every time, instead of a single element so the type constraint is wrong.

Edit: Probably JRuby impementation is (was?) correct
Edit2: If you look at the specs it's clear that the type constraint is wrong: https://github.com/gdotdesign/elm-github-install/blob/master/spec/utils_spec.rb
